-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Drinkki CASCADE;
DROP TABLE IF EXISTS Tyyppi CASCADE;
DROP TABLE IF EXISTS Ainesosa CASCADE;
DROP TABLE IF EXISTS Mittayksikko CASCADE;
DROP TABLE IF EXISTS RaakaAine CASCADE;